import Link from 'next/link';

export default () => (
    <>
        <section style={{ backgroundColor: '#065f46', textAlign: 'center' }}>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
            <h1>Homepage</h1>
        </section>
        <Link href="/test">Go to test page</Link>
    </>
);
